# Describes the format for Habitica service
api_call:
  fields:
    name:
      required: true
      example: "xxxNotAValidNickxxx"
      selector:
        text:
    path:
      required: true
      example: '["tasks", "user", "post"]'
      selector:
        object:
    args:
      example: '{"text": "Use API from Home Assistant", "type": "todo"}'
      selector:
        object:
cast_skill:
  fields:
    config_entry: &config_entry
      required: true
      selector:
        config_entry:
          integration: habitica
    skill:
      required: true
      selector:
        select:
          options:
            - "pickpocket"
            - "backstab"
            - "smash"
            - "fireball"
          mode: dropdown
          translation_key: "skill_select"
    task:
      required: true
      selector:
        text:
get_tasks:
  fields:
    config_entry: *config_entry
    filter:
      collapsed: true
      fields:
        type:
          required: false
          selector:
            select:
              options:
                - "habit"
                - "daily"
                - "todo"
                - "reward"
              mode: dropdown
              translation_key: "type"
              multiple: true
              sort: true
        priority:
          required: false
          selector:
            select:
              options:
                - "trivial"
                - "easy"
                - "medium"
                - "hard"
              mode: dropdown
              translation_key: "priority"
              multiple: true
              sort: false
        task:
          required: false
          selector:
            text:
              multiple: true
        tag:
          required: false
          selector:
            text:
              multiple: true
        keyword:
          required: false
          selector:
            text:
