fetch_connections:
  target:
    entity:
      integration: swiss_public_transport
      domain: sensor
  fields:
    limit:
      example: 3
      required: true
      selector:
        number:
          min: 0
          max: 15
          step: 1
