codecov:
  branch: dev

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.09
      required:
        target: auto
        threshold: 1
        paths:
          # Specify paths for required coverage
          - homeassistant/components/*/config_flow.py
          - homeassistant/components/*/device_action.py
          - homeassistant/components/*/device_condition.py
          - homeassistant/components/*/device_trigger.py
          - homeassistant/components/*/diagnostics.py
          - homeassistant/components/*/group.py
          - homeassistant/components/*/intent.py
          - homeassistant/components/*/logbook.py
          - homeassistant/components/*/media_source.py
          - homeassistant/components/*/recorder.py
          - homeassistant/components/*/scene.py

    patch:
      default:
        target: auto
      required:
        target: 100
        threshold: 0
        paths:
          # Specify paths for required patch coverage
          - homeassistant/components/*/config_flow.py
          - homeassistant/components/*/device_action.py
          - homeassistant/components/*/device_condition.py
          - homeassistant/components/*/device_trigger.py
          - homeassistant/components/*/diagnostics.py
          - homeassistant/components/*/group.py
          - homeassistant/components/*/intent.py
          - homeassistant/components/*/logbook.py
          - homeassistant/components/*/media_source.py
          - homeassistant/components/*/recorder.py
          - homeassistant/components/*/scene.py

comment: false

# Carry forward flags for partial tests
flag_management:
  default_rules:
    carryforward: false
  individual_flags:
    - name: full-suite
      paths:
        - ".*"
      carryforward: true
