call_method:
  target:
    entity:
      integration: squeezebox
      domain: media_player
  fields:
    command:
      required: true
      example: "playlist"
      selector:
        text:
    parameters:
      example: '["loadtracks", "album.titlesearch=Revolver"]'
      advanced: true
      selector:
        object:
call_query:
  target:
    entity:
      integration: squeezebox
      domain: media_player
  fields:
    command:
      required: true
      example: "albums"
      selector:
        text:
    parameters:
      example: '["0", "20", "search:Revolver"]'
      advanced: true
      selector:
        object:
search:
  target:
    entity:
      integration: squeezebox
      domain: media_player
  fields:
    command:
      required: true
      selector:
        select:
          multiple: false
          options:
            - label: Albums
              value: albums
            - label: Artists
              value: artists
            - label: Tracks
              value: tracks
            - label: Playlists
              value: playlists
            - label: Genres
              value: genres
            - label: Favorites
              value: favorites
            - label: Players
              value: players
    return_items:
      required: true
      selector:
        number:
          min: 1
          max: 10000
          mode: box
    search_string:
      required: false
      example: Revolver
      selector:
        text:
