reload_device_list:

refresh_device_status:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: lgthinq

get_device_profile:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: lgthinq

get_device_status:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: lgthinq

post_device_status:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: lgthinq
    value:
      required: true
      example: "{'operation': {'airConOperationMode': 'POWER_OFF'}}"
      selector:
        text:

button:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: lgthinq
          domain: media_player
    button:
      required: true
      example: "LEFT"
      selector:
        text:

command:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: lgthinq
          domain: media_player
    command:
      required: true
      example: "system.launcher/open"
      selector:
        text:
    payload:
      example: >-
        target: https://www.google.com
      advanced: true
      selector:
        object:

select_sound_output:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: lgthinq
          domain: media_player
    sound_output:
      required: true
      example: "external_speaker"
      selector:
        text:
