upload:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: google_photos
    filename:
      required: true
      selector:
        object:
    album:
      required: true
      selector:
        text:
