preset:
  target:
    entity:
      domain: linkplay
  fields:
    preset:
      example: 1
      required: true
      default: 1
      selector:
        number:
          min: 1
          max: 10
          mode: box
