override_schedule:
  target:
    entity:
      integration: "husqvarna_automower"
      domain: "lawn_mower"
  fields:
    duration:
      required: true
      selector:
        number:
    override_mode:
      required: true
      example: "mowing"
      selector:
        select:
          options:
            - "mowing"
            - "parking"
