# Describes the format for available Telegram client services

send_message:
  target:
    entity:
      domain: device_tracker
      integration: telegram_client
  fields:
    target_username:
      example: me, telegram, BotFather, +380987654321
      selector:
        text:
    target_id:
      example: -1000000000000, 1000000000000
      selector:
        number:
    message:
      example: The garage door has been open for 10 minutes.
      selector:
        text:
    reply_to:
      selector:
        number:
          mode: box
    parse_mode:
      selector:
        select:
          options:
            - html
            - markdown
    link_preview:
      selector:
        boolean:
    file:
      selector:
        object:
    force_document:
      selector:
        boolean:
    clear_draft:
      selector:
        boolean:
    keyboard:
      selector:
        object:
    inline_keyboard:
      selector:
        object:
    keyboard_resize:
      selector:
        boolean:
    keyboard_single_use:
      selector:
        boolean:
    silent:
      selector:
        boolean:
    supports_streaming:
      selector:
        boolean:
    schedule:
      selector:
        datetime:
    comment_to:
      selector:
        number:
          mode: box
    nosound_video:
      selector:
        boolean:
