set_dehumidity:
  target:
    entity:
      domain: climate
  fields:
    dehumidity:
      required: true
      selector:
        number:
          min: 10
          max: 50
          unit_of_measurement: "%"

trigger_air_cleaning_event:
  target:
    entity:
      domain: climate
  fields:
    event:
      required: true
      selector:
        select:
          options:
            - label: "3 Hours"
              value: "3hour"
            - label: "24 Hours"
              value: "24hour"

cancel_air_cleaning_event:
  target:
    entity:
      domain: climate

set_air_cleaning_mode:
  target:
    entity:
      domain: climate
  fields:
    mode:
      required: true
      selector:
        select:
          options:
            - label: "Off"
              value: "0"
            - label: Constant Clean
              value: "1"
            - label: Automatic
              value: "2"

toggle_air_cleaning_mode:
  target:
    entity:
      domain: climate
  fields:
    mode:
      required: true
      selector:
        select:
          options:
            - label: "Off"
              value: "0"
            - label: Constant Clean
              value: "1"
            - label: Automatic
              value: "2"

trigger_fresh_air_event:
  target:
    entity:
      domain: climate
  fields:
    event:
      required: true
      selector:
        select:
          options:
            - label: "3 Hours"
              value: "3hour"
            - label: "24 Hours"
              value: "24hour"

cancel_fresh_air_event:
  target:
    entity:
      domain: climate

set_fresh_air_mode:
  target:
    entity:
      domain: climate
  fields:
    mode:
      required: true
      selector:
        select:
          options:
            - label: "Off"
              value: "0"
            - label: Automatic
              value: "1"

toggle_fresh_air_mode:
  target:
    entity:
      domain: climate
  fields:
    mode:
      required: true
      selector:
        select:
          options:
            - label: "Off"
              value: "0"
            - label: Automatic
              value: "1"
